DROP TABLE BLOG;

CREATE TABLE BLOG
(
    BLOG_NUM    VARCHAR2(20) NOT NULL,
    USERR_NUM    VARCHAR2(20) NOT NULL,
    BLOG_NAME    VARCHAR2(50) NOT NULL,
    BLOG_BACK    VARCHAR2(300),
    BLOG_INT    VARCHAR2(300),
    STATE    VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN BLOG.BLOG_NUM IS '블로그번호';

COMMENT ON COLUMN BLOG.USERR_NUM IS '회원번호';

COMMENT ON COLUMN BLOG.BLOG_NAME IS '블로그이름';

COMMENT ON COLUMN BLOG.BLOG_BACK IS '블로그배경';

COMMENT ON COLUMN BLOG.BLOG_INT IS '블로그소개';

COMMENT ON COLUMN BLOG.STATE IS '상태';

COMMENT ON TABLE BLOG IS '블로그';

CREATE UNIQUE INDEX BLOG_PK ON BLOG
( BLOG_NUM );

ALTER TABLE BLOG
 ADD CONSTRAINT BLOG_PK PRIMARY KEY ( BLOG_NUM )
 USING INDEX BLOG_PK;


DROP TABLE CATEGORY;

CREATE TABLE CATEGORY
(
    CATE_NUM    VARCHAR2(20) NOT NULL,
    BLOG_NUM    VARCHAR2(20) NOT NULL,
    CATE_NAME    VARCHAR2(50) NOT NULL,
    CATE_CLASS    VARCHAR2(50),
    STATE    VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN CATEGORY.CATE_NUM IS '카테고리번호';

COMMENT ON COLUMN CATEGORY.BLOG_NUM IS '블로그번호';

COMMENT ON COLUMN CATEGORY.CATE_NAME IS '카테고리명';

COMMENT ON COLUMN CATEGORY.CATE_CLASS IS '카테고리분류';

COMMENT ON COLUMN CATEGORY.STATE IS '상태';

COMMENT ON TABLE CATEGORY IS '카테고리';

CREATE UNIQUE INDEX CATEGORY_PK ON CATEGORY
( CATE_NUM );

ALTER TABLE CATEGORY
 ADD CONSTRAINT CATEGORY_PK PRIMARY KEY ( CATE_NUM )
 USING INDEX CATEGORY_PK;


DROP TABLE HEART;

CREATE TABLE HEART
(
    POST_NUM    VARCHAR2(20) NOT NULL,
    BLOG_NUM    VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN HEART.POST_NUM IS '포스팅번호';

COMMENT ON COLUMN HEART.BLOG_NUM IS '블로그번호';

COMMENT ON TABLE HEART IS '공감';


DROP TABLE POST;

CREATE TABLE POST
(
    POST_NUM    NUMBER NOT NULL,
    BLOG_NUM    VARCHAR2(20) NOT NULL,
    FILE_NUM    VARCHAR2(20),
    POST_TITLE    VARCHAR2(50) NOT NULL,
    POST_CON    VARCHAR2(3000) NOT NULL,
    POST_TIME    DATE NOT NULL,
    STATE    VARCHAR2(20) NOT NULL,
    CATE_NUM    VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN POST.POST_NUM IS '포스팅번호';

COMMENT ON COLUMN POST.BLOG_NUM IS '블로그번호';

COMMENT ON COLUMN POST.FILE_NUM IS '파일번호';

COMMENT ON COLUMN POST.POST_TITLE IS '제목';

COMMENT ON COLUMN POST.POST_CON IS '내용';

COMMENT ON COLUMN POST.POST_TIME IS '작성시간';

COMMENT ON COLUMN POST.STATE IS '상태';

COMMENT ON COLUMN POST.CATE_NUM IS '카테고리번호';

COMMENT ON TABLE POST IS '포스팅';

CREATE UNIQUE INDEX POST_PK ON POST
( POST_NUM );

ALTER TABLE POST
 ADD CONSTRAINT POST_PK PRIMARY KEY ( POST_NUM )
 USING INDEX POST_PK;


DROP TABLE USERR;

CREATE TABLE USERR
(
    USERR_NUM    VARCHAR2(20) NOT NULL,
    USERR_ID    VARCHAR2(30) NOT NULL,
    USERR_PW    VARCHAR2(30) NOT NULL,
    USERR_NIC    VARCHAR2(30) NOT NULL,
    USERR_NAME    VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN USERR.USERR_NUM IS '회원번호';

COMMENT ON COLUMN USERR.USERR_ID IS '회원아이디';

COMMENT ON COLUMN USERR.USERR_PW IS '비밀번호';

COMMENT ON COLUMN USERR.USERR_NIC IS '닉네임';

COMMENT ON COLUMN USERR.USERR_NAME IS '이름';

COMMENT ON TABLE USERR IS '회원';

CREATE UNIQUE INDEX USERR_PK ON USERR
( USERR_NUM );

ALTER TABLE USERR
 ADD CONSTRAINT USERR_PK PRIMARY KEY ( USERR_NUM )
 USING INDEX USERR_PK;








CREATE SEQUENCE SEQ_POSTNUM
START WITH 200
INCREMENT BY 1
MAXVALUE 500
NOCYCLE
NOCACHE;